
name: GitHub Actions Build and Deploy Demo

on:
    push:
      branches:
         - main

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
          - name: checkout
            uses: actions/checkout@master
            # 安装依赖
          - name: install
            run: yarn
            # 打包构建
          - name: build
            run: yarn build
            # 部署运行
          - name: Deploy
            uses: JamesIves/github-pages-deploy-action@v4.3.0
            with:
                ACCESS_TOKEN: ${{ secrets.REACT_TOKEN }}
                BRANCH: gh-pages
                FOLDER: dist

